services:
  gui:
    image: teramis-gui:latest
    ports:
      - 8080:3000
    depends_on:
      database:
        condition: service_healthy
        restart: true
    volumes:
      - ${TERAMIS_SCAN_TARGET}:/teramis-watchdog/agents
    environment:
      - PGHOST=database
      - PGPORT=5432
      - PGUSER=${PGUSER:-teramis}
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE:-teramis}
      - TERAMIS_SCAN_TARGET=/teramis-watchdog/agents
      - NEXTAUTH_URL=http://localhost:8080
      - NEXT_PUBLIC_COMPANY_NAME=${TERAMIS_COMPANY_NAME}
  watchdog:
    image: teramis-watchdog:latest
    depends_on:
      database:
        condition: service_healthy
        restart: true
    volumes:
      - ${TERAMIS_SCAN_TARGET}:/teramis-watchdog/agents
    environment:
      - PGHOST=database
      - PGPORT=5432
      - PGUSER=${PGUSER:-teramis}
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE:-teramis}
      - TERAMIS_SCAN_TARGET=/teramis-watchdog/agents
    command:
      - "python"
      - "agent_sync.py"
      - "--watch"
    #extra_hosts:
    #  - "database:${PGHOST:-172.17.0.1}"
  database:
    image: teramis-postgres:latest
    ports:
      - 6868:5432
    volumes:
      - ${TERAMIS_DB_DIR:-../data}:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${PG_SUPERUSER:-postgres}
      - POSTGRES_PASSWORD=${PG_SUPERUSER_PASSWORD}
      - POSTGRES_DB=postgres
      - PGUSER=${PGUSER:-teramis}
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE:-teramis}
      - PGPORT=5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER} -d ${PGDATABASE}; && sleep 2" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
